John Lions code

Files taken from
PDP-11/Distributions/research/Dennis_v6/v6root.tar.gz
except l.s, renamed here to low.s from
PDP-11/Distributions/research/Ken_Wellsch_v6/root.v6.tar.gz

low.s and conf.c are generated by conf/mkconf.c


Chapters and where the code is taken from (from original /usr/sys):

1init:

param.h systm.h seg.h proc.h user.h low.s conf/m40.s ken/main.c ken/slp.c ken/prf.c ken/malloc.c

2traps

reg.h ken/trap.c ken/sysent.c ken/sys1.c ken/sys4.c ken/clock.c ken/sig.c

3swap

text.h ken/text.c buf.h conf.h (conf.c) dmr/bio.c dmr/rk.c

4files

file.h filsys.h ino.h inode.h ken/sys2.c ken/sys3.c ken/rdwri.c ken/subr.c ken/fio.c ken/alloc.c ken/iget.c ken/nami.c ken/pipe.c

5char

tty.h dmr/kl.c dmr/tty.c dmr/pc.c dmr/lp.c dmr/mem.c


v6d-left:
conf  dmr  ken  run

v6d-left/conf:
data.s  m45.s  mkconf.c  sysfix.c

v6d-left/dmr:
cat.c  dc.c  dh.c  dhdm.c  dhfdm.c  dn.c  dp.c  hp.c  hs.c  ht.c  partab.c  rf.c  rp.c  sys.c  tc.c  tm.c  vs.c  vt.c

v6d-left/ken:


param.h systm.h seg.h proc.h user.h (low.s) conf/m40.s ken/main.c ken/slp.c ken/prf.c ken/malloc.c

reg.h ken/trap.c ken/sysent.c ken/sys1.c ken/sys4.c ken/clock.c ken/sig.c

text.h ken/text.c buf.h conf.h (conf.c) dmr/bio.c dmr/rk.c

file.h filsys.h ino.h inode.h ken/sys2.c ken/sys3.c ken/rdwri.c ken/subr.c ken/fio.c ken/alloc.c ken/iget.c ken/nami.c ken/pipe.c

tty.h dmr/kl.c dmr/tty.c dmr/pc.c dmr/lp.c dmr/mem.c


